# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170718_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occupation',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
