# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170719_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='details',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='complete',
        ),
    ]
